project:
  type: website


website:
  title: "Home"
  image: "artificial-intelligence.png"
  favicon: "artificial-intelligence.png"
  page-navigation: true
  bread-crumbs: true
  search:
    show-item-context: true
    type: overlay
  navbar:
      background: light
      logo: artificial-intelligence.png
      logo-alt: "AI for Pumps logo."
      collapse-below: lg
      left:
        - text: "Writings"
          href: data/writings/index.qmd
        - text: "About"
          href: about.qmd




  page-footer:
    left: |
      Proudly supervised  by
      [![](https://scholar.googleusercontent.com/citations?view_op=medium_photo&user=JebIw2QAAAAJ&citpid=2){fig-alt="Prof. Dr. Mohamed farid khalil" width=65px}](https://scholar.google.com.eg/citations?user=JebIw2QAAAAJ&hl=en)
    center:
      - text: "About"
        href: about.qmd
    right:
      # - icon: youtube
      #   href: https://twitter.com/quarto_pub
      #   aria-label: Quarto Twitter
      - icon: github
        href: https://github.com/MohammedTwheed/mtk-bachelor-project-website
        aria-label: mtk-bachelor-project-website GitHub



format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    include-after-body: js.html
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px


bibliography: references.bib

execute:
  freeze: auto
  # cache: true


