---
pagetitle: "UNDER_CONSTRUCTION"
page-layout: custom
section-divs: true
toc: false
css: index.css
editor: source
description: | 
  this website host your bachelor project about artificial intelligence applications in centrifugal pumps with main focus on regression tasks including symbolic regression and more.

execute:
  echo: false
---

::: {.hero-banner}
::: {.content-block}
::: {.grid .column-page}
::: {.headline .g-col-lg-6 .g-col-12 .g-col-md-12}
::: h1
AI Applications in Pumps
:::

### this website will host all of our work on bachelor project with dr farid


to know more about us
-   [About](about.qmd)

:::

<!-- ```{r}
#| classes: '.g-col-lg-6 .g-col-12 .g-col-md-12'
#| warning: false
source("carousel.R")
carousel("gallery-carousel", 5000, 
         yaml.load_file("carousel.yml"))
``` -->

:::
:::
:::
:::


::: {.content-block}
:::{.features}

:::{.feature}

# Our latest paper 
## Beyond Trial and Error: A Machine Learning Approach to Optimal Centrifugal Pump Impeller Trimming


    This paper proposes a genetic algorithm (GA)-based methodology to optimize hyperparameters for artificial neural networks (NNs) applied to pump impeller trimming. Traditionally, impeller trimming relies on expert knowledge and empirical methods, leading to time-consuming and potentially suboptimal outcomes. This work introduces a data-driven approach using NNs trained to predict the impeller diameter (D) and pump power (P), which can be calculated from flow rate (Q), density (ρ), head (H), and efficiency (η) using the equation P = (Q * ρ * g * H) / η.  based on the desired operating point (flow rate (Q) and head (H)). A GA is employed to identify the optimal NN hyperparameters, including hidden layer size, training function, activation function, and maximum epochs. The goal is to minimize the mean squared error (MSE) between the network's predictions and the actual performance data. The paper details the implementation of the GA optimization process and discusses the key components and their significance in achieving optimal impeller trimming through NN predictions. 
::: {.learn-more}
[Learn more »](data/writings/posts/trimming_15-4-2024/index.qmd)
:::

:::

:::
:::


